# Basic site settings
title: "Vikas Kumar"
description: "Personal website and blog of Vikas Kumar"
url: "https://vikask13.github.io"  # no trailing slash
baseurl: ""  # leave empty for user/organization site (i.e., github.io site)

# Author (optional)
author:
  name: "Vikas Kumar"
  email: "your-email@example.com"

# GitHub Pages-compatible theme
theme: jekyll-theme-primer

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Permalinks for blog posts
permalink: /:year/:month/:day/:title/

# Build settings
future: true  # show future-dated posts
lsi: false
safe: true
incremental: false

# Social links (optional, shown only if added manually in layout)
social_links:
  - name: GitHub
    url: https://github.com/vikask13
  - name: LinkedIn
    url: https://www.linkedin.com/in/YOUR-LINKEDIN/
  - name: Email
    url: mailto:your-email@example.com

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Vikas Kumar"
      comments: true
